---
title: "Geography Cluster Working Document"
Group Members: 
  - "Rae Traver-Fallick"
  - "Hayden Steinmann"
  - "Jessie Wang"
  - "Kayla Tillmon"
date: 2026-09-30

---

### Stage #1 Reflection 

The overarching theme of our group is the cause and effect of prisons and their geography. Collectively we took an interest in things such as gerrymandering, regional differences, how the location of correctional facilities impact the surrounding area, and how geography impacts the school environments of young adults. Across Rae and Jessie’s work rural towns and economies are especially relevant; prison gerrymandering typically shifts representation from urban areas to rural settings, which is due to the placement of prisons in primarily rural areas; such placement is within the scope of Jessie’s investigation. Hayden and Kayla both plan to look at how geographical differences can impact how individuals interact with the legal system. In short, Jessie will investigate why a prison is placed where it is, Rae will look at the state and national political implications of that placement, Hayden will explore how school/neighborhood segregation impacts juveniles, and Kayla narrows that down into examining the effects on how, specifically, Black individuals are treated within the legal system through regional differences.

We’ve started to compile a list of relevant pieces of literature to our topics and have already started to see certain overlaps. We’re hoping that these similarities will also be helpful when it comes to looking for datasets. Kayla and Hayden are both taking a comparative approach by looking at regional differences. While Hayden is looking at a smaller scale of just Mecklenburg County and Kalya at the general “North” and “South”, the overlap in investigating how a person’s place can impact their outcomes will be a shared theme. One general theme will be the idea of representation, which is a highly social concept, with far reaching societal impacts, so we hope that we can all help capture this more humanistic side together. Rae and Jessie may both rely on datasets relating to the geographic location of correctional facilities. Hayden and Rae will also likely both be looking at how people are geographically dispersed both demographically and socioeconomically. We all hope that we can use this research cluster as a way to bounce ideas off of each other despite there being differences between our projects. Having a general idea of what each of us is working on will be helpful as we’ll be able to see how each other's projects progress and the background that surrounds them. 

