{
  "hash": "56a25cb8adeb061deace7e35d7a9f278",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Initial Questions\nauthor: Nikko Stevens\nexecute:\n  code-fold: true\n---\n\n# Stage 2: Initial Explorations of the Dataset.\n::: callout-note\nThis example captures my own real, work-in-progress thinking about this dataset.  I haven't gone back and made any revisions. I am writing this page at the same time as I'm asking these questions. What is in this dataset? What kinds of questions might I want to ask as I drill down?\n:::\n\n## About\n\n### Dataset\nThe dataset is [Executions in the United States, 1608 - 2002: The Espy File](https://www.icpsr.umich.edu/web/NACJD/studies/8451).  It is stored in the `_data` folder, and the entire set of downloaded files from ICPSR is in the folder `ICPSR-08451`.  Below, you'll see that I'm using inscrutable column names.  They are labled in the file `projects/demo/_data/ICPSR_08451/DS0001/08451-0001-Codebook.pdf`\n\n### Research Question\nMy initial research question is pretty vague -- _\"Are there trends in the crimes for which people have been executed in the United States?\"_ And if I'm being honest, this isn't the right question for someone with both my disciplinary background and my technical skillset/interests.  I'm more interested in how this dataset is shaped, and what I might learn from the kinds of values I'm seeing in it.  (This is a more [inductive approach](https://socialsci.libretexts.org/Bookshelves/Social_Work_and_Human_Services/Scientific_Inquiry_in_Social_Work_(DeCarlo)/06:_Linking_Methods_with_Theory/6.03:_Inductive_and_deductive_reasoning).)\n\n## First question: gender\nI notice that there is a field that defines the sex of the person.  What's the gender breakdown within this dataset?\n\n::: {#70ec2808 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nfrom pyprojroot import here # this helps us navigate tricky path stuff between local runs and quarto builds\n\n# Load the data using here() with the path from the project root\nfile_path = here(\"projects/demo/_data/ICPSR_08451/DS0001/08451-0001-Data.tsv\")\ndf = pd.read_csv(file_path, sep='\\t')  # Remember!! use '\\t' for tab-separated (which this data is)\n\n# how many people executed were women? (where V19 = 2)\ncount_v19 = len(df[df['V19'] == '2']) # NOTE - this column is a varchar, so you need to put quotes around your integer. \n\n# total rows in dataset\ntotal_rows = len(df)\n\n# lil percent count\ngender_breakdown = count_v19 / total_rows * 100\n\nprint(\"Number of women: \", count_v19)\nprint(\"Total Rows \", total_rows)\nprint(f\"Percentage of women: \",  gender_breakdown)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNumber of women:  364\nTotal Rows  15268\nPercentage of women:  2.384071260151952\n```\n:::\n:::\n\n\nAt this point, I know that 364 women (2.38%) of all people executed in this dataset were women. Within those 364, what else can I learn?\n\n## Occupation\n\n::: {#8539b87e .cell execution_count=2}\n``` {.python .cell-code}\n# Let's assign that subset to it's own data frame so that we can work just with it\nwomen = df[df['V19'] == '2']\n\n# What kinds of jobs (col V21) did these women have? \nmost_common_jobs = women['V21'].value_counts().head(10)\n\nprint(most_common_jobs)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nV21\n610    154\n       102\n328     51\n197     11\n593      8\n509      5\n440      4\n719      4\n327      3\n731      2\nName: count, dtype: int64\n```\n:::\n:::\n\n\nOkay, whatever job is 610 is by far the most common, with \"no occupation recorded\" (NULL) the second most common. 328, a distant second, and 197 less than 3% (11 women).  Let's go to the Codebook and see what these jobs are. \n\n```         \ncode - occupation\n610 - Slave\n328 - Housewife\n197 - Domestic Servant\n593 - Servant\n509 - Prostitute\n440 - Nurse\n719 - Waitress\n327 - Housekeeper\n731 - Widow\n```\n::: callout-note\nYIKES.  I wasn't expecting to see \"Slave\" as an occupation in this dataset. This makes sense with the broad history of the US - does it make \"sense\" within this dataset? \n::: \n\n## Trigger warning! \nBased on what we're seeing here (and some browsing I'm doing in the explorer), it looks like the majority of women executed were executed during slavery in the United States. Let's see what the median year in this dataset is - does this make sense?\n\n::: {#a0920e35 .cell execution_count=3}\n``` {.python .cell-code}\nmedian_year = women['V14'].median()\nprint(median_year)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1826.5\n```\n:::\n:::\n\n\nOkay, the median year is 1826. (Remember, the [13th Amendment](https://www.archives.gov/milestone-documents/13th-amendment) which constitutionally abolished slavery was in 1856) This validates the occupation data we're seeing. Let's also check if there was race (column V5) recorded. In the codebook, these are the values for race:\n`0 M Do Not Know; NA 1 White 2 Black 3 Native American 4 Asian-Pacific Il 5 Hispanic 6 Other`\n\n::: {#7c21a667 .cell execution_count=4}\n``` {.python .cell-code}\n# What was recorded for race? \nmost_common_race = women['V5'].value_counts().head(3)\n\nprint(most_common_race)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nV5\n2    198\n1    138\n      20\nName: count, dtype: int64\n```\n:::\n:::\n\n\n## Crimes?\nOkay, this is still making sense. A few more general questions about women. Across all, what were their crimes?\n\n::: {#c8eaaed8 .cell execution_count=5}\n``` {.python .cell-code}\nmost_common_crimes = women['V10'].value_counts().head(10)\n\nprint(most_common_crimes)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nV10\n1     225\n9      26\n16     20\n10     20\n       18\n33     12\n40      8\n6       7\n8       5\n36      5\nName: count, dtype: int64\n```\n:::\n:::\n\n\n```         \ncode - crime\n1 - Murder\n9 - Witchcraft\n16 - Arson\n10 - Robbery-Murder\n33 - Poisoning\n40 - Attempted Murder\n6 - Conspiracy to Murder\n8 - Slave revolt\n36 - Unspecified Felony\n```\n### Witchcraft?\nWoof.  Okay.  This also makes sense.  All of this is part of finding one's way around the dataset.  I am _expecting_ that the women executed for witchcraft were white (based on Hollywood movies about witch trials)\n\n::: {#d8fcb66b .cell execution_count=6}\n``` {.python .cell-code}\n# reminder, crime V10, race V5\n# we are asking slightly more complicated questions now\n# of the women where V10 = 9 (witchcraft), what were their races?\n\nrace_of_witches = women[women['V10']==\"9\"][\"V5\"].value_counts().head(3)\nprint(race_of_witches) # or rather, women convicted of witchcraft\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nV5\n1    26\nName: count, dtype: int64\n```\n:::\n:::\n\n\n### Slave Revolt?\nWe're seeing data that matches historical expectations (though we must always be careful when making these!).  Women executed for witchcraft were exclusively white in the dataset.  I would similarly expect women convicted of \"Slave Revolt\" to be Black.  Does this track? \n\n::: {#a8d0eed1 .cell execution_count=7}\n``` {.python .cell-code}\n# reminder, crime V10, race V5\n# we are asking slightly more complicated questions now\n# of the women where V10 = 8 (slave revolt), what were their races?\n\nrace_of_revolters = women[women['V10']==\"8\"][\"V5\"].value_counts().head(3)\nprint(race_of_revolters) # or rather, women convicted of 'slave revolt'\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nV5\n1    4\n2    1\nName: count, dtype: int64\n```\n:::\n:::\n\n\nSurprise!  That is also majority white women (4 to 1).  Who were these women? \n\n#### let's put names to the numbers\n\n::: {#e13c639e .cell execution_count=8}\n``` {.python .cell-code}\n# (NOTE, you could do this in the explorer, but then it wouldn't be permanent. This helps us revisit this data any time as we keep thinking through our questions)\n\n# the 5 women convicted and executed for 'slave revolt'\nrevolters = women[women['V10']=='8']\n\n# let's make printing easier/prettier and grab just the columns we need\n# V7 = name, V6 = age, V5 = race, V11 = method of ex, V14 year, V16 state\n\npretty_table = revolters[['V7', 'V6', 'V5', 'V11', 'V14', 'V16']].copy()\npretty_table.columns = ['Name', 'Age', 'Race', 'Method', 'Ex Year', 'State']\n\npretty_table\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Name</th>\n      <th>Age</th>\n      <th>Race</th>\n      <th>Method</th>\n      <th>Ex Year</th>\n      <th>State</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>4822</th>\n      <td></td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1730</td>\n      <td>22</td>\n    </tr>\n    <tr>\n      <th>7505</th>\n      <td>ABIGAIL (VANINBURGH)</td>\n      <td></td>\n      <td>1</td>\n      <td>1</td>\n      <td>1712</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7506</th>\n      <td>SARAH (PELS)</td>\n      <td></td>\n      <td>1</td>\n      <td>1</td>\n      <td>1712</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7539</th>\n      <td>KERRY MARGARET</td>\n      <td></td>\n      <td>1</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7541</th>\n      <td>HUGHSON SARAH</td>\n      <td></td>\n      <td>1</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## 1741\nOkay, something happened in 1741 with Margaret Kerry and SArah Hughson (I'm guessing).  A quick web search of these two names reveals (1) A website called \"executedtoday.com\" (grim), with [details](https://www.executedtoday.com/2016/06/12/1741-john-hughson-sarah-hughson-and-peggy-kerry-so-abandoned-to-confederate-with-slaves/) of this situation.  It was apparently part of the \"New York Slave Rebellion of 1741\" ([Brittanica Entry](https://www.britannica.com/event/New-York-slave-rebellion-of-1741))\n\nIf this dataset is complete, I would expect to see a lot of people executed in New York (`state == 36`) in 1741. The Brittanica entry reads \"As a result of the rumors, false confessions, and finger-pointing, approximately 30 Black people and 4 white people (the Hughsons, Kerry, and Ury) were executed, and some 80 more people, mostly Black but some white, were exiled.\"   Does the dataset have this data?\n\n### Checking the Uprising\n\n::: {#153e2315 .cell execution_count=9}\n``` {.python .cell-code}\n# we're going back to the entire dataset now and checking on the year 1741\nrevolters = df[df['V14'] == 1741]\n\nprint(\"Total Executions in 1741\", len(revolters))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTotal Executions in 1741 43\n```\n:::\n:::\n\n\nThis is close. What about in New York State?\n\n::: {#4d9000e3 .cell execution_count=10}\n``` {.python .cell-code}\n# we're going back to the entire dataset now and checking on the year 1741\nrevolters = df[df['V14'] == 1741]['V16']\n\nprint(\"Top 3 states with executions in 1741\", revolters.value_counts().head(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTop 3 states with executions in 1741 V16\n36    34\n34     2\n45     2\nName: count, dtype: int64\n```\n:::\n:::\n\n\nOkaaaay!  I'm not sure if this is the focus I want to pursue for the next phase, but this data seems to line up really tidily with this historical account.  I wasn't expecting to find _any_ of this when I grabbed this dataset, but this feels like a fine stopping point for this line of inquiry.  Let's put names to these folks, too, and then take a step back for another set of questions.\n\n### the humans of New York, 1741\n\n::: {#8ae3e54e .cell execution_count=11}\n``` {.python .cell-code}\n# filter for year of execution (V14) and state of execution (V16)\nny_revolters = df[(df['V14'] == 1741) & (df['V16'] == 36)]\n\npretty_table = ny_revolters[['V7', 'V6', 'V5', 'V11', 'V14', 'V16']].copy()\npretty_table.columns = ['Name', 'Age', 'Race', 'Method', 'Ex Year', 'State']\n\npretty_table\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Name</th>\n      <th>Age</th>\n      <th>Race</th>\n      <th>Method</th>\n      <th>Ex Year</th>\n      <th>State</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>7531</th>\n      <td>TOM</td>\n      <td></td>\n      <td>2</td>\n      <td></td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7532</th>\n      <td>COOK (COMFORT)</td>\n      <td></td>\n      <td>2</td>\n      <td>10</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7533</th>\n      <td>CAESAR (VAARCK)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7534</th>\n      <td>PRINCE (ABOYNEAU)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7535</th>\n      <td>CUFFEE (PHILIPSE)</td>\n      <td></td>\n      <td>2</td>\n      <td>10</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7536</th>\n      <td>QUACK (ROOSEVELT)</td>\n      <td></td>\n      <td>2</td>\n      <td>10</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7537</th>\n      <td>CUFFEE (GOMEZ)</td>\n      <td></td>\n      <td>2</td>\n      <td>10</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7538</th>\n      <td>CAESER (PECK)</td>\n      <td></td>\n      <td>2</td>\n      <td>10</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7539</th>\n      <td>KERRY MARGARET</td>\n      <td></td>\n      <td>1</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7540</th>\n      <td>HUGHSON JOHN</td>\n      <td></td>\n      <td>1</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7541</th>\n      <td>HUGHSON SARAH</td>\n      <td></td>\n      <td>1</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7542</th>\n      <td>ALBANY (CARPENTER)</td>\n      <td></td>\n      <td>2</td>\n      <td>10</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7543</th>\n      <td>DICK CURACOA</td>\n      <td></td>\n      <td>2</td>\n      <td>10</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7544</th>\n      <td>FRANCIS (BOSCH)</td>\n      <td></td>\n      <td>2</td>\n      <td>10</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7545</th>\n      <td>BEN (MARSHALL)</td>\n      <td></td>\n      <td>2</td>\n      <td>10</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7546</th>\n      <td>CATO (COWLEY)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7547</th>\n      <td>FORTUNE(VANDERSPIEGL)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7548</th>\n      <td>QUASH (RUTGERS)</td>\n      <td></td>\n      <td>2</td>\n      <td>10</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7549</th>\n      <td>CATO (PROVOOST)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7550</th>\n      <td>CATO (SHURMUR)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7551</th>\n      <td>HARRY (KIPP)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7552</th>\n      <td>PRINCE (DUANE)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7553</th>\n      <td>TONEY (LATHAM)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7554</th>\n      <td>YORK (MARSCHALK)</td>\n      <td></td>\n      <td>2</td>\n      <td>11</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7555</th>\n      <td>WILL (WARD)</td>\n      <td></td>\n      <td>2</td>\n      <td>10</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7556</th>\n      <td>FORTUNE (WATSON)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7557</th>\n      <td>FRANK (RYKER)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7558</th>\n      <td>GALLOWAY (RUTGER)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7559</th>\n      <td>HARRY (MIZREAL)</td>\n      <td></td>\n      <td>2</td>\n      <td>10</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7560</th>\n      <td>OTHELLO (DE LANCEY)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7561</th>\n      <td>QUACK (WALTERS)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7562</th>\n      <td>VENTURE (TIEBOUT)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7563</th>\n      <td>WAN (SARLEY)</td>\n      <td></td>\n      <td>2</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n    <tr>\n      <th>7564</th>\n      <td>URY JOHN</td>\n      <td></td>\n      <td>1</td>\n      <td>1</td>\n      <td>1741</td>\n      <td>36</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nOh for f's sake.  I see that there were different methods of execution that, not perfectly, but pretty tidily map to race.  People who were white (`race == 1`) were hanged (`1`), while Black people were sometimes hanged, but also executed by methods `10` and `11` (burning, and hanging in chains).  This dataset just keeps giving.  \n\n",
    "supporting": [
      "overview_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}