project:
  type: website

website:
  title: "SDS316: Data of the US Criminal Legal System"
  description: "Applicaiton Domain (context depth) class that focuses on understanding and working with data related to crime, policing, incarceration, detention, and other aspects of the Prison Industrial Complex (PIC) in the US"
  navbar:
    left:
      - href: index.qmd
        text: Hxome
      - href: syllabus.qmd
        text: Syxllabus
      - href: schedule.qmd
        text: Schxedule
      - href: projects.qmd
        text: Projxects
      - href: lectures.qmd
        text: Selecxted Lectures

format:
  html:
    theme: cosmo # Quarto comes with many built-in themes (bootswatch)
    toc: true

execute:
  freeze: auto