---
title: "Assignments"
---

Extra detail about each type of assignment and the final project below.

## Class summary sheets

### Why we do it

Reflecting on the material is an important part of working in an application domain. These give you practice responding to ethical/domain-specific questions in the same way you will be asked to do so in your data science career.

### What it is

Class summary sheets are handouts that you drop into the box at the end of some classes answering a question related to that day’s lecture or an aspect of the reading. Some students do not do well speaking in class, others prefer speaking to writing. These sheets give some students a chance to communicate in their strongest medium, and others the opportunity to strenghten their impromptu written communication skills.

### How it's graded

These are graded credit/no credit and *cannot be made up* if you are absent from class. The only way to get *no credit* for a sheet that you filled out is if you obviously did not do the reading and obviously are writing answers that are completely irrelevant.

We will have \~25 class meetings this semester, and will only do these on the 12 or 13 seminar days. Full credit for this section is **10** sheets.

## Leading class discussion

### Why we do it

This assignment gives you the opportunity to practice a few important skills: communicating summary information, asking questions about new/complex material, speaking in public (😬), and moderating and facilitating conversations about complex subjects.

::: callout-important
You are responsible for signing yourself up to be a class leader. If you cannot attend class that day, you are responsible for switching with another student. [Class Leader Schedule](https://docs.google.com/spreadsheets/d/1oqzW3GjvwdGwQpR57L7JWsS9Wvx-1Sehy_xs4PBAoBo/edit?gid=0#gid=0)
:::

### What it is

Leading class discussion involves preparing materials about the day’s topic, summarizing the reading, and then leading class through \~15 minutes of discussion.

When it's your day to lead, you'll need to create a branch and make edits to the day's lecture slides before class. The lecture files are markdown in the `lectures` folder. You'll find the appropriate file (week number, class number (for example the Class 1 of Week 2 `week2-c1.qmd`) . You'll know where to add your slides by reading the code and finding the comment:

``` html
<!-- Discussion Leader: Add your slides here -->
```

When it's your turn to lead discussion, you will make these edits:

1.  Create **1** slide with

    1.  A link to a piece of inside-written (or other authors who are system-impacted) journalism or reporting about something related to the reading, the coursework, or your particular research project. We do this because it's important to listen to people who have directly experienced the criminal legal system.

    2.  A link to a current news article related to the topic.

    3.  1 - 2 sentences about how these are related to the day's topics

2.  Create **2** slides with an overview of the main points of the reading.

3.  Create **1** slide with discussion questions. Here's a popular guide for [how to ask good discussion questions](https://avidly.lareviewofbooks.org/wp-content/uploads/2016/09/Some-Notes-On-How-To-Ask-A-Good-Question-About-Theory-That-Will-Provoke-Conversation-And-Further-Discussion-From-Your-Colleagues-2-2.pdf).

4.  Open a [pull request]{.underline} containing JUST these **4** slides (and any associated images that you require which should be stored in `lectures/images`) and assign it to me by **twelve pm** the day of the class. Note that the PR [must]{.underline} pass all tests, so try not to put it off until the last minute in case tests fail!

    1.  if you open a PR with failing tests and don't fix it yourself, I will fix it and merge before class but/and that will impact your grade on that portion of the assignment

During class:

-   At a certain point (likely different in each class), you'll come to the front of the room and spend **7-10 minutes** discussing the links you found and giving us an overview of the reading.

-   Then, you'll have **13-15** minutes to lead discussion with your peers. I won't participate unless called on. :)

### How its Graded

These are graded credit/no credit for each of 7 components:

-   four complete slides (each credit/no credit)

-   PR open and building (no credit for an open PR that fails to build - so remember to *start early!*)

-    presented slides for 7-10 minutes

-   facilitated discussion for 13-15 minutes

## Midterm and Final Evaluations
The midterm and final checkins will be a mix between a conversation and an oral exam.  You'll schedule a 20-minute block to come to my office where we will talk generally about how the class is going for you and how your project is going.  I'll then ask you to respond to two questions, one about the reading, and one about the technical stack we're using. All questions will be shared at least a week before the exams.

### How its graded
These are graded credit/no credit along the following dimensions

- scheduled an evaluation and arrived on time (within ~3 minutes of the start)
- demonstrated an ability to talk honestly about the reading
- demonstrated an ability to talk honestly about the project (this does _not_ mean that your project needs to be going well.  It only means that you are aware of how the project is going and are able to talk about it with a level of detail that demonstrates that you're engaged)
- demonstrated an ablilty to talk through the technical answer with at least about 75% accuracy
- demonstrated an ability to respond to the reading question citing evidence from the text 


## Research Project

The research project will have many component parts and will be a project that we scaffold over the course of the semester so that you will have the chance to continue to refine and revise your thinking. This project includes submitting many smaller tasks, including research questions, a bibliography, a literature review, first draft, final draft, and a code + documentation bundle. Each component will be graded separately.

### Stage 1 - Exploration + Workflow

During the first stage of the project, we're practicing:

-   getting comfortable in the IDE, including customizing it as needed for our tasks (let the tools work for us!)

-   getting comfortable with git and the Github pull request workflow (let the tools work for us!)

-   developing our research questions and building lists of resources and literature to review

-   forming research clusters to support our research

#### Final Deliverable

In a pull request:

-   you've made a project in the project folder, which is a copy of the  `projects/template` folder with only the files you're working with at this stage.  So, don't copy a bunch of meaningless template files into your project - delete all of the ones you don't need yet.  You can add them later when the phase is appropriate.

-   Within that folder, you've:

    -   updated the yaml front matter of `index.qmd` to be accurate to your project

    -   added the yaml category for your research group (we will ID these in class)

    -   filled out all of the sections of `research-plan.qmd`

-   In the `datasets.qmd` file, you've added **five** datasets that you've found that could be useful to your inquiry. You can create a new subheading if it's appropriate, or spread the links across pre-existing sections


As a research cluster, you will write three paragraphs (about 350 words) about the connections you see between your projects, and how you are planning to use the cluster to support your individual research projects. Name this file following the pattern `g.cluster-name.qmd` and put it directly in the main `projects` folder (it will be a sibling to your individual project folders). If your project cluster was about Women In Prison, you might name your file `g.women-in-prison.qmd` Only *one* of your cluster members will add this to their Stage 1 Pull Request, so talk about it amongst yourselves to figure out who will do this.

### Stage 2 - Analyzing Data & Scaffolding the Report

During the second stage, we're actively working on data analysis and making sure that all work is building successfully. This includes:

-   writing python code to analyze the data

-   drafting preliminary writing about the technical/quantitative steps you're taking

-   discussing your results with your research cluster

-   exploring data visualizations

#### Key Deliverables
_More details about these deliverables and what you'll turn in will appear closer to the due date!_

-   Project and Report scaffold

-   Updated (if necessary) research questions / investigation description


### Stage 3 - Building and Deploying

During the third stage of the project, we're practicing:

-   Foreclosing possibilities (aka, committing to a direction even if you're uncertain about the results)

-   Making decisions about the best ways to visualize information

-   Telling stories with data / questioning what data may be telling us

#### Key Deliverables
_More details about these deliverables and what you'll turn in will appear closer to the due date!_

-   final-first-draft report

-   draft abstract
 

### Stage 4 - Reflection + Refinement

During the first stage of the project, we're practicing:

-   revising key findings

-   viewing and critiquing others' work

-   reflecting on the process and what we've learned

#### Key Deliverables

-   final report

-   Updated `g.cluster-name.qmd` file to list all of the projects from the group.

-   self-reflection (private)

## ⚠️ Submitting Work

With a few exceptions, 100% of your class work will be performed in a fork of [this repository](https://github.com/drnikko/sds316). \<💡[How to fork](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo)\>

In order for your work to be complete and accepted,

-   you will do all of your work in a descriptively and appropriately named branch that includes your name.  For example, if I were going to make a branch to add to the week's discussion slides, I might name it `stevens-w2-slides.` A branch for my first project deliverable might be called `nikko-project-deliverable`.  I'm not setting hard-and-fast rules about what you should call the branch, only that you keep in mind that there are many people making many branches and there has to be a way to identify what a branch is for based ONLY on the name of it.

- you will open a pull request (PR) with *just* the changes you're trying to merge in \<💡[how to open a PR](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)\>

-   that PR will build successfully

-   you will make any necessary changes requested by your peers (when a review is required) and to ensure the build succeeds

-   you update the PR with those changes

-   I will then merge the PR into the `main` branch and delete your branch and the cycle will begin again!