---
title: "Class Log"
---

## Sept 9

List of questions in no particular order:

-   How has the prison industrial complex system contributed to the "death" of the American dream?

-   Rico, how effective is this?

-   How are cases handled or processed in criminal court?

-   Average waiting trial period?

-   How are people prioritized in the queue?

-   Can records be expunged? Basically, what does due process look like, and how does it play out?

-   I've been in a lot of classes that discuss the surveillance state and the panopticon Foucault, so I want to learn more about it in the context of real data. What does this look like in practice?

-   What about the EJI, the Equal Justice Initiative?

-   How is organized crime treated differently in the U.S. legal system?

-   How is blackness treated in the U.S. legal system?

-   Where do human disasters like plane crashes, cyber attacks, factory explosions, and chemical spills fit into the system?

-   What are some resistances against surveillance, like face paint or body coverings?

-   I want to learn more about how race maps onto arrests and prison data as a national pattern or trend. How is this an inherent part of the prison industrial complex related to racial capitalism.

-   In regarding holding patterns, what are the differences between prisons and jails?

-   Are there biases involved in holding procedures for prisoners based on identity?

-   How do we think about data workers training AI models and their work contracts and the context that they see.

-   Why are non-violent offenders sentenced to long prison sentences?

-   How do we think about the identity of victims and perpetrators.

-   What about recidivism?

-   What about prison abolition?

-   What about recidivism?

-   What about search for and disposal of evidence?

-   How are public and private prisons different?

-   What is political polarization in the legal system? Are there geographical differences?

-   Where does redlining fit in?

-   What are urban versus rural legal and criminal conditions?

-   How does healthcare work within the criminal system?

-   What about the school-to-prison pipeline?

-   What about victim desires in terms of sentencing?

-   How do they keep track of people?

-   Do people's files ever get lost?

-   How do we think about the concept of being able to pay for better lawyers or attorneys?

-   How do state laws about what's legal or not legal disseminate?

-   What is pretty privilege in mugshots?

-   Police presence in neighborhoods?

-   How are people disabling flock cameras and surveillance?

-   What is trans healthcare in prison?

-   How do guards get jobs? Why do they go along with treating prisoners poorly?

-   What about Scandinavian or alternative approaches to punishment?

-   What happens when people leave the system? How can this transition be made easier?

-   To what extent does media perception affect convictions?

-   Why can you charge children as adults? Who decides that?

-   What is the prison system's relationship to the foster care system.

-   How do mothers in prison get custody back?

-   What is sentencing in the South versus the North?

-   Who is Brian Stevenson, the criminal justice lawyer?

-   What about risk assessments and using technology to determine if someone will commit crimes again.

-   What about prisons and small towns?

-   What about white collar crimes?

-   What about the public perception of prisons and perceptions of prisons' purpose?

-   What happens to immigrants or people on visas or work study after they are accused of a crime.

-   What happens to people who are wrongly accused of crime and convicted, but exonerated out years later? Do they still have a record on file?

-   To what extent does public opinion on social media affect how someone gets executed, good or bad?

-   How does the U.S. legal system handle foreign criminals in the U.S.

-   What about the internal prison economy?

-   What about people charged with sex crimes?

-   Are they releasing people with old marijuana convictions?

-   What about gender nonconforming and transphobic violence? I feel like there's not enough clarity and information.

-   How do we think about AI tech companies and user harm, like chatbots and suicide?

-   How does artificial intelligence change the U.S. criminal justice system?

-   What about enslavement to the prison-industrial complex pipeline?

-   How do long-term cases get traced and changed depending on law changes?

-   What about solitary confinement?

-   What are the differences between women's and men's rights and Protection differences.

-   Who and how decides if an offender is juvenile?

-   Who decides whether an offender deserves rehab and healing or punishment?

-   What about the use of DNA evidence to reverse indictments?

-   What about the concept of paying to get out of jail and the power of money.

-   What about cannabis laws?

-   What about the war on drugs?

-   What about women in prison?

-   What about politicians funding prisons?

-   Who benefits the most from prison?

-   What about politicians in support of prisons?

-   What are the qualities of prison facilities?

-   What about white women tears?

-   What about surveillance body cameras and neighborhoods?

-   What about mnematic warfare?

-   What about low-income housing leading to low-income jobs leading to foster care, leading to prison, leading to racism