

The class is broken into five "sprints," each having 5 class sessions.  Each sprint will follow roughly the same schedule, so that you always know what to expect. 

Sprint:
1 lecture - new information! lots of it
2 lab - new information + hands on
3 studnet tech prez + lab - pop quiz! hands on + new information
4 student content prez + lecture - review key concepts / discuss integration
(end-of-sprint deliverables DUE)



25 class sessions in the semester
[draft syllabus](https://docs.google.com/document/d/1gcTregTaJKTzPuUeHbQEtI3e_38JzYVwixEPD9OOP5c/edit?tab=t.0#heading=h.z4q1b6mv44zf)

## Key deliverables

1. a list of questions (in class)

2. A 3 item list of sources to start answering ONE question  (committed to class github via pull resquest)

3. A list of research clusters (submitted by someone from each cluster in a PR - skill: PRs in fast-moving code base / integrating upstream changes)

4. a lit review from each research cluster, including source datasets

5.  final research questions from everyone (submitted via PR)

6. initial dataset proof of concept / data description

7. initial analysis and findings

8. final findings

9. narrative



## Extra Credit -- Technical Demonstrations
- Show us two data visualizations using matplotlib after we've set it up
- Walk us through opening a github pull request 
- Explain the github fork/branch process
- Demonstrate making github commits in the terminal
- Show us how to set up python notebooks in Positron
- Demonstrate 3 Quality of Life (QoL) terminal improvements or Positron customizations you've made
- 






Data Science text for reading and reference: https://wesmckinney.com/book/plotting-and-visualization 

(way down the line)

0. 

1. ethics statement & positionality (how do we relate to ourselves and the data and ourselves via the data)

2. Possible datasets. 


Examples that we might discuss:
- https://www.marlo.works/posts/last-meals/ 
- Subreddit r/dataisbeautful search for 'crime' - https://www.reddit.com/r/dataisbeautiful/search/?q=crime&cId=8425b48d-f890-4701-8214-13691b12bf04&iId=d38f4365-5c7f-4bae-9d96-176bcab85e50 


## Week 1 Homework
- By W2.C1: 
  - Read Intro & Chapter 1 of _Digitze and Punish_. Bring your book to class.
  - Sign up for a discussion leader slot on the [assignments](assignments.qmd#leading-class-discussion) page which has a link to the [Class Leader Schedule](https://docs.google.com/spreadsheets/d/1oqzW3GjvwdGwQpR57L7JWsS9Wvx-1Sehy_xs4PBAoBo/edit?gid=0#gid=0)

- By W2.C2: Install everything you need for the [tech stack](tech-stack.qmd).  Come to office hours if you're struggling. 