---
title: Initial Questions
author: Jessie Wang
execute:
  code-fold: true
---

# Stage 2.1: Initial Explorations of the Dataset.


## About

### Dataset
The dataset is [US Federal and Private Prisons](https://github.com/miolow/US_prisons/blob/master/allprisons.csv).  It is stored in the `data` folder, and the csv is in two sections for some reason, so we will wrangle.

```{python}

import pandas as pd
from pyprojroot import here # this helps us navigate tricky path stuff between local runs and quarto builds

# Load the data using here() with the path from the project root
file_path = here("projects/jessie_project/data/allprisons.csv")
df = pd.read_csv(file_path, sep=',') 

# one = df[:216] 
# two = df[217:]

# one = one.rename(columns = {"coordinates": "geometry", "coordinates_rev": "coordinates"})
# two = two.rename(columns={"PrisonName": "name"})
# two["longitude"] = two["longitude"].astype(str)
# two["latitude"] = two["latitude"].astype(str)
# two["coordinates"] = "(" + two["longitude"] + ", " + two["latitude"] + ")"




# # combined = pd.concat([one, two], sort=False)
# # combined[216:218]

# df = pd.concat([one, two], axis=0, join='outer', ignore_index=False)
# df.head(10)
```

### Research Question
My first research question is _"Where are prisons located?"_ Which is vague. But I want to focus on prison systems in the US. 

## Total
Whats the total distribution of prisons accross states?
```{python}
common_states2 = df['State'].value_counts().head(10)

print(common_states2)
```

Texas             88
Florida           77
North Carolina    59
California        54
New York          48
Illinois          45
Georgia           43
Virginia          43
Colorado          39
Oklahoma          34
Name: count, dtype: int64

## Federal
Since the data set is split into federal and not, let's check what the distribution is of federal vs not federal

```{python}

# how many federal prisons are there?
count_gov = len(df[(df['govprisons'] == 1.0) | (df['stateprison'] == 0.0)]) 

# total rows in dataset
total_rows = len(df)

# lil percent count
gov_breakdown = count_gov / total_rows * 100

print("Number of Federal Prisons: ", count_gov)
print("Total Rows ", total_rows)
print(f"Percentage of prisons: ",  gov_breakdown)
```

Number of Federal Prisons: 973
Total Rows  1107
Percentage of prisons:  87.8952122854562

Hmm.. lets zoom in

## Federal Prisons by State
What is the state breakdown?

```{python}

# Assign Subset
federal = df[(df['govprisons'] == 1.0) | (df['stateprison'] == 0.0)]

# What are the most common states that these prisons are in?
most_common_states = federal['State'].value_counts().head(10)

print(most_common_states)

```

State
Florida           70
Texas             60
North Carolina    56
New York          46
Illinois          45
Virginia          41
California        40
Georgia           35
Michigan          30
Pennsylvania      29


The most common state is Florida! Im not 100% surprised but not unexpected.

## Public?

let's check the distribution of prisons for public prisons
```{python}

# how many federal prisons are there?
count_pub = len(df[df['private'] == 0.0]) 

# total rows in dataset
total_rows = len(df)

# lil percent count
pub_breakdown = count_pub / total_rows * 100

print("Number of Public Prisons: ", count_pub)
print("Number of Private Prisons: ", total_rows - count_pub)
print("Total Rows ", total_rows)
print(f"Percentage of prisons: ",  pub_breakdown)
```

Number of Public Prisons:  973
Number of Private Prisons:  134
Total Rows  1107
Percentage of prisons:  87.8952122854562

Majority are public!

## state distribution of public?
What states make up most of the distribution?
```{python}

public = df[df['private'] == 0.0]
public.head(10)
most_common_states2 = public['State'].value_counts().head(10)

print(most_common_states2)
```

State
Florida           70
Texas             60
North Carolina    56
New York          46
Illinois          45
Virginia          41
California        40
Georgia           35
Michigan          30
Pennsylvania      29
Name: count, dtype: int64

It's still florida at the top. Big surprise. But because most of the prisons are public, let's look at private next.

## state distribution of private?
What states make up most of the distribution?
```{python}

priv = df[df['private'] == 1.0]
priv.head(10)
most_common_states3 = priv['State'].value_counts().head(10)

print(most_common_states3)
```

Texas         28
Colorado      19
California    14
Arizona        9
Oklahoma       9
Georgia        8
Florida        7
Tennessee      6
New Mexico     5
Louisiana      4
Name: count, dtype: int64


Oooh, now this is different. Texas has the most public prisons, it doesnt seem like the rest are that proportional to how many total prisons the state has. 

This dataset doesnt have a lot of other information, so the next step for me is to find a new dataset about the demographics.