---
title: Research Plan
author: Hayden Steinmann
execute:
  code-fold: true
---

## Phase 1 Research Questions

1. How have the geographic patterns of school/neighborhood segregation in Mecklenburg County shaped patterns of juvenile and young adult criminal legal system involvement?
2. How does residential segregation shape the geography of police encounters in Mecklenburg County? 
3. How has the geographic distribution of racial and socioeconomic school segregation in Mecklenburg County changed over time?

## Personal Motivation
Growing up in Charlotte, NC I experienced the Charlotte-Mecklenburg School (CMS) system firsthand. Charlotte has a deep rooted history of school desegregation, yet still has evident patterns of racial and economic geographical divide. Throughout the three CMS schools that I attended, it became clear that several inequities existed. I’m interested in exploring the history and data surrounding the extent to which these inequalities exist. I hope to look at the geography of schools and neighborhoods and see the connections that may exist between how young people experience and interact with the criminal legal system. Being able to put statistical meaning to the environment and experiences I grew up with will be eye-opening and motivating.  

## Broader Relevance
The school to prison pipeline is a relatively well known systemic phenomenon. This concept has numerous contributing factors with many interconnected parts. Looking at the relationship that this concept has with geographic and segregated matters is of extreme importance. CMS provides an important case as the district moved from a nationally recognized court-ordered desegregation to substantially greater racial and socioeconomic segregation following changes in school assignment policy. Some research has been done surrounding this issue, but the spatial overlap between school and neighborhood segregation and youth involvement in the criminal legal system is less studied. I hope to bring light to these issues by examining the geographic disparities that continue to persist to this day.  

## Example Projects

**[Mapping the School to Prison Pipeline in North Carolina, 1972-2016](https://www.icpsr.umich.edu/web/NACJD/studies/38141/summary?tenant=icpsr&archive=nacjd#):** I thought this project was super interesting as it looks at the relationship between keeping schools safe and keeping students attached to school. The investigated whether different school policies decreased rates of in-school violence in the short term and/or increased rates of conviction/incarceration in the long run. I liked the data sources that they pulled from and some of the statistical analysis that they did.

**[The Segregation Tracking Project](https://edopportunity.org/segregation/explorer/):** This project is super super cool! They’ve created a map of the country tracking the segregation that exists. They have map layers for residential segregation, student segregation, regional segregation, and more. This is a big part of what I want to look like so I’m hoping to take inspiration from some of the maps that they’re made and data that they’ve pulled from. 

**[Beyond Black and White](https://beyondblackandwhite.github.io/):** While this project does have some capabilities that no longer work, I thought it was a super helpful timeline of how racial disparities have shifted throughout the education system in CMS. I hope to touch on most if not all of the historical pieces that they included (ex. plessy v. ferfuson, brown v. board, swann v. cms, etc.)

## Relevant Literature

**[School Segregation, Educational Attainment and Crime: Evidence from the end of busing in Charlotte-Mecklenburg](https://www.nber.org/papers/w18487):** This is an important study as it looks at how students living in the same neighborhood but on opposite sides of newly drawn school boundaries have different relationships with the criminal-legal system. I think this study will be pretty foundational to my research as it highlights how a student's environment can greatly impact the outcomes that they may face later in life. 

**[The School to Prison Pipeline: Long-Run Impacts of School Suspensions on Adult Crime](https://www.nber.org/papers/w26257):** This paper looks at how school discipline may have an impact on how students are exposed to the criminal legal system from a young age. They look at how things such as high suspension rates may have a bigger impact in the long run. I think this could be really interesting to look at, especially in terms of how the demographics of a school correlates to the type of in school discipline that a school receives. 

**[Cumulative Racial and Ethnic Disparities Along the School-to-Prison Pipeline](https://journals.sagepub.com/doi/10.1177/00224278211070501):** This paper takes a similar approach to the above one but focuses more on the racial and ethnic disparities surrounding school suspension and expulsion. It offers lots of theoretical and statistical frameworks which I hope will help guide some of the analyses and data that I use.

**[What determines school segregation? The crucial role of neighborhood factors](https://www.sciencedirect.com/science/article/pii/S0047272720301997):** This paper looks at how much of school segregation can be fully attributed to neighborhood characteristics vs school-specific factors. They also look at how this differs amongst urban areas. Since I’m not sure which level of segregation I’m going to look at yet I think this paper will be helpful in making that decision.

**[The Effects of School Desegregation on Crime](https://www.nber.org/papers/w15380):** This paper introduces an interesting idea as it looks at the effect that court-ordered school desegregation has on crime. They go on to explain how this also has an impact on the police system as a whole as they notice that police spending decreased years following these court orders. I want to make sure to include this as it shows the impact that it has on the greater community and not just students and schools.

**[The State of our Children](https://www.tuesdayforumcharlotte.org/wp-content/uploads/2020/05/200521StateOfOurChildren.pdf):** The statistics in this report are a bit dated, but I think it hints at some super important trends such as adjudications, dispositions, and other juvenile justice issues. It is very detailed with regards to the racial/ethnic breakdown of these topics.

**[Juvenile Justice in Mecklenburg County](https://rmjj.org/wp-content/uploads/2019/11/2019JuvenileJusticeAwarenessMonth-FINALREPORT.pdf):** This is a community-oriented report that specifically addresses juvenile justice in Mecklenburg County. It discusses the history of school segregation, school discipline, policy change, and the racial disparities throughout. It has a bunch of cool graphs and staggering statistics that I think will help give me a good basis. 

**[The Impact of Busing in Charlotte](https://www.ncanchor.org/anchor/impact-busing-charlotte):** This is a unique format as it’s a collection of oral histories rather than a typed out research study. It includes perspectives from Black and white students who experienced this integration and varying points in time. I think this will be extremely helpful in humanizing the impact of school segregation. 

**[Educational Experiences: Voices of Incarcerated Male Youth & School-to-Prison Pipeline](https://jajjs.org/ojs/index.php/jajjs/article/view/49/33):** This brings in a super important perspective as the project is based on interviews of incarcerated young men and their educational experiences. They explain how their school and personal lives played a role in this outcome. Discussing things such as unhealthy environments, substance abuse, and criminal activity. 

**[UNCC Goldmine (oral histories and digital archives)](https://goldmine.charlotte.edu/record/26774?v=aud%2Caud):** These three oral histories and transcripts all discuss the integration of schools. Two come past students with one being from the CMS superintendent. These first-hand accounts will likely be helpful in characterizing what these times were like and how they compare to now. I was only able to include one link here, but I have two more for the other speakers.