---
title: "Stage 2: Initial Data Exploration"
author: 
  - "Julia Laney"
date: 2026-10-7
---

# WA State Police & Social Spending
## Project Stage 2
### Research question: How does King County allocate its resources between police spending and social spending?

Initially, I want to explore the dataset containing Washington state fiscal information. To simplify this exploration, I am looking at just the fiscal year 2025.

```{python}
#python cell = CMD Shift I

import pandas as pd
from pyprojroot import here

#importing dataset containing fiscal info by entity
df = pd.read_csv('OSTAllEntity.csv')
```

```{python}
#I want to look at just the 2025 fiscal year for now

#the data included a space behind each year
df["FiscalYear"] = df["FiscalYear"].str.strip()

df_2025 = df[df["FiscalYear"] == "FY 2025"]
```

## How should I rigorously define "police spending" and "social spending"?

After just visually looking through some of the data, I'm seeing that a lot of spending items in this data are for municipal governments to support local law enforcement, courts, and crime prevention. This is making me consider that "police spending" may be a narrow term for this project, though I don't think I should expand this term to "criminal justice spending". A better term for this type of spending is something I am thinking about moving forward.

I used King County to obtain the spending items used in the mapping process because it is the largest county per capita and includes the city of Seattle. I figured it would likely have the most spending items, so when I applied the mapping to other counties, it would (hopefully) include all possible items.

## What are the major spending categories? How can I classify each row of data into a category? 

```{python}
#now I want to look at spending categories

#using King county because it's the largest county in the state, and I noticed it had the most spending categories
df_2025[df_2025["EntityTitle1"] == "King County"]["TaxTitle4"].unique()
```

Looking at the spending categories, I'll sort each into police/law enforcement spending, criminal justice legal system spending, social spending, and other spending by making a new column "SpendingCategory" in the 2025 dataframe. A portion of spending goes to courts, which I don't think should be included as police/law enforcement spending. For example, one spending item is judges' salaries, this shouldn't be included in police spending. This goes back to my earlier note about how I need to define "police/law enforcement" spending.

```{python}
#creating a new column with 3 categories of spending using a map
category_map = {
    "County Arterial Road Preservation": "Other",
    "County Auditor Historical Document Preservation Assistance": "Other",
    "County Autopsy Cost Assistance": "Other",
    "County Criminal Justice Assistance": "Criminal Legal System",
    "County DUI Enforcement Assistance": "Police/Law Enforcement",
    "County Elected Prosecuting Attorney Salaries - State Contribution": "Criminal Legal System",
    "County Juvenile Crime Enforcement Assistance": "Police/Law Enforcement",
    "County Legal Financial Obligation Grants": "Criminal Legal System",
    "County Superior Court Judge Salaries and Benefits - State Contribution": "Criminal Legal System",
    "Court Appointed Special Advocate Coordinator Grants": "Social",
    "Court Interpreter Assistance": "Other",
    "District and Municipal Court Judges Salaries - State Contribution": "Criminal Legal System",
    "Family and Juvenile Court Improvement Grants": "Social",
    "Federal Flood Control Lease Payments": "Other",
    "Federal Secure Rural Schools and Community Self-Determination Act Fund  - County Roads or Public Schools": "Other",
    "Law Enforcement Officers and Firefighters Retirement System - Plan 2 State Contribution": "Other",
    "Leasehold Excise Tax Sharing": "Other",
    "Liquor Excise Tax Sharing": "Other",
    "Liquor Profits Sharing": "Other",
    "Marijuana Excise Tax": "Other",
    "Motor Vehicle Fuel Tax Additional Sharing - County": "Other",
    "Motor Vehicle Fuel Tax Sharing - County": "Other",
    "Multimodal Transportation Account Sharing - County": "Other",
    "Parents Representation Program": "Social",
    "Public Defense Improvement Grants": "Criminal Legal System",
    "Public Utility District Privilege Tax Sharing": "Other",
    "Runaway and At-Risk Youth (Becca) County Juvenile Court Costs": "Social",
    "State Lodging Tax Sharing": "Other",
    "State Payments in Lieu of Taxes - Natural Area Preserves and Natural Resources Conservation Areas": "Other",
    "State Payments of Deferred Property Tax": "Other",
    "State Vessel Registration Fees": "Other",
    "Streamlined Sales and Use Tax Mitigation Payments": "Other",
    "Timber Excise Tax Sharing": "Other"
}

df_2025["SpendingCategory"] = df_2025["TaxTitle4"].map(category_map)

#let's check that this categorizing worked
df_2025[["EntityTitle1", "TaxTitle4", "Amount6", "SpendingCategory"]] #it did!

#some missing values are present here because the first observations in the df correspond to Aberdeen (a city) and the cities and counties have some naming differences for the same spending items
print(df_2025.head(n=15))
```

## What spending category did King County spend the most on in 2025?

```{python}
#making a copy of the 2025 df looking just at King county
df_2025_king = df_2025[df_2025["EntityTitle1"] == "King County"].copy()

print(df_2025_king.head(n=15))
```

```{python}
#the integers in Amount6 were being treated as strings 
#df_2025["Amount6"] = (df_2025["Amount6"].str.replace(",","").str.replace("(", "-")
 #   .str.replace(")", "").astype(float)) #the df used () to represent negative numbers

#remaking df after cleaning Amount6
df_2025_king = df_2025[df_2025["EntityTitle1"] == "King County"].copy()

#finding the totals of each spending category
king_cat_totals = (df_2025_king.groupby("SpendingCategory")["Amount6"].sum())

print(king_cat_totals)
```

These numbers look really off! After reading more about the source of this data, this appears to be showing money that Washington distributes to local governments through taxes, revenue sharing programs, and grants. I initially understood the data as budgetary information.

## Is this data relevant to my project?

Maybe? This data doesn't capture police spending vs. social spending but contains information about how much criminal justice funding each county receives from the state. This is not really a main point of my project but it could be a supplementary point.

```{python}
#taking a look at pierce county
df_2025_pierce = df_2025[df_2025["EntityTitle1"] == "Pierce County"].copy()

#same process I did for King
pierce_cat_totals = (df_2025_pierce.groupby("SpendingCategory")["Amount6"].sum())

print(pierce_cat_totals)
```

```{python}
#per capita funding
pierce_pc = pierce_cat_totals["Criminal Legal System"] / 946288
king_pc = king_cat_totals["Criminal Legal System"] / 2344939

print("Pierce County:", pierce_pc)
print("King County:", king_pc)
```

In 2025, Pierce County received about $12.01 per capita in distributions related to the criminal legal system. King County received about $11.12 per capita in distributions related to the criminal legal system. It's important to note that this is just state funding and not the counties' own criminal legal system spending. I'm curious - is this difference an effect of each counties' crime rates?