---
title: Research Plan
author: Catherine Xu
execute:
  code-fold: true
---

## Phase 1 Research Questions

1. How does the presence and relative density of surveillance technologies vary by neighborhood in Manhattan? 
2. In what way is the presence and relative density of surveillance technologies in Manhattan affected by the racial makeup of the neighborhood in terms of arrests, convictions, etc.? 
3. Are there any differences in the _types_ of surveillance technologies used based on the racial makeup of the neighborhood? What implications do these differences have on justice-impacted individuals?

## Personal Motivation
Write about 100 words about your motivation for undertaking this topic.  Why are you _personally_ interested in this material?  You can be as personal or as general as you wish here, but this section is about YOUR interest in the material
To be transparent, I do not have a personal connection to Manhattan or New York City in general as I am not from there. I would be open to living and working there someday, but I thought Manhattan would be an interesting case study just because of how much data there likely exists regarding the demographics of Manhattan and the wide reach of police presence in the city. It is also compelling to me because of the stark socioeconomic and racial disparities that exist between each neighborhood or area of Manhattan, which, based on much historical precedent, has significant implications for the level of police presence and institutional discrimination in any given geographical region. 

## Broader Relevance
Write about 100 words discussing why you think the answers to these questions might matter to others. Is this an understudied topic?  Have the conclusions you've been seeing about it been wrong or missing something? This is your answer to the "so what?" question
Given the rapid advancement and availability of big data and surveillance technologies, I wanted to investigate what kind of an impact this development has had on the rate of arrests, convictions, and potentially re-arrests in Manhattan by neighborhood, and also address whether or not there is a relationship between the differential usage of these technologies and the racial makeup of a given neighborhood. It is not necessarily an understudied/unexplored topic, especially in recent years, but with New York's influence on a national _and_ global scale, I thought it would be important to address some of the human consequences and inequities that surveillance technology has perpetuated/exacerbated. 

## Example Projects

Link to three example projects that are related to your questions or how you'd like to display your results.  List them like so:

**[Race and Ethnicity Map of New York](https://bestneighborhood.org/race-in-new-york-ny/):** I wanted to potentially create a spatial visualization (interactive map) of the police presence or surveillance cameras by neighborhood/region of Manhattan. To make it a trivariate map I'm hoping to find a way to layer the racial demographics of each neighborhood on top of the measure of surveillance. I think this visualization method will most effectively communicate the relationship between my variables. 

**[Dismantle NYC's Surveillance State](https://static1.squarespace.com/static/6786da0226ec38320c099635/t/69a74f26da718d22c0b57a82/1772572454655/2026.2.26_STOP%2BReport_Dear%2BMamdani_FINAL.pdf):** This project is a report and petition for Mayor Mamdani to act on his initiatives to dismantle the various forms of harmful government surveillance in NYC. It includes a lot of helpful background and data points, including the estimated costs of the specified reforms, which I will use to contextualize and broaden my coverage and discussion of the types of racially discriminatory surveillance technologies in NYC policing. 

**[Vital City: Who's the Guard Really Guarding in US Cities?](https://www.vitalcitynyc.org/reality-check-whos-the-guard-really-guarding-in-us-cities/):** I liked how this project highlighted the discrepancy between the cities that Trump's executive orders involving police force/action targeted and the actual prevalence of crime and violence in those cities. I want to build a similar narrative with my visualizations that highlights the areas of Manhattan that are most heavily surveilled/policed and compare it with the actual rate of violent crime that exists in those areas, with the idea that surveillance technologies are largely based on databases that are far from neutral, but based on arrest data that discriminates against certain racial groups. 

## Relevant Literature

Build a **ten** item literature review for work related to your questions. 

As you consider which 10 to include, try to satisfy these criteria:

- 1 - 2 written by someone on the inside or system impacted
- 3ish non-academic sources
- at least 5 academic sources
- no more than 2 items that we've discussed in class / from the syllabus

No need to include a full citation.  Instead, list them:

**[In the Image of Injustice: A Critical Examination of AI, Surveillance, and Systemic Racism in the United States](https://journals.sagepub.com/doi/full/10.1177/21533687261455743):** This article examines the detrimental impact of AI and its associated technologies in the conducting of crime risk assessments and justifications of surveillance. It covers how these technologies have significant error rates for people of color and are based on algorithms that resulted from a history of racial discrimination and over-policing in communities that are predominantly made up of people of color, thereby challenging the notion that AI and surveillance technologies are neutral/unbiased tools of justice. 

**[Types of AI Surveillance](https://www.jstor.org/stable/resrep20995.8):** This article is one of the sources that I am planning to use mostly for background and context about the different types of AI-driven surveillance technologies 