---
title: Research Plan
author: Jessie Wang
execute:
  code-fold: true
---

## Phase 1 Research Questions

1. Where are prisons located?
2. What are the demographics of each location?
3. What went into the decision to build the prisons?

## Personal Motivation
I've never really thought about where prisons were built, or what they looked like. I want to know about what went into the decisions to build a prison there: was it  the local government who decided it? What did the local population think? Does it have anything to do with the proximity to "criminals"? I hope to answer these questions this semester.

This is also a topic I think I will be able to stomach through this semester. My original idea involved media coverage, yet there is no data set for that. Other subjects and topics may dive into darker territory, and I’m not sure if I’ll be able handle researching such dark topics all the time.


## Broader Relevance

I am wondering if there are any reasons behind building prisons relating to racism, classism, or otherwise. I believe that it is important to examine this aspect of systemic oppression, if it exists, that is not studied very much; I haven't seen a lot of articles about how prison locations are decided. There is the theory that prisons are built to exploit black and brown prisoners for the benefit of the towns nearby, but I did come across an article that disproved it. So, I am wondering what else factors in that decision.


## Example Projects

Link to three example projects that are related to your questions or how you'd like to display your results.  List them like so:

**[Every Prison in the US](https://unfoundedlabs.com/maps/prison/):** Since this project is also exploring location, I want to display a map like this project does. I want to have more text though, rather than just an exploration of the prisons

**[Disease Related Deaths](https://public.tableau.com/app/profile/josh.tapley/viz/DiseaseRelatedDeaths/CountyMap):** This project displays many maps, and I think displaying the locations of prisons along side population demographics is a good idea. Visually comparing the maps beside my writing will enhance my argument.

**[How the US Generates Electricity](https://www.carbonbrief.org/mapped-how-the-us-generates-electricity):** Yes, this is the format that I was envisioning. A map (or two, or more) followed by prose writing. This is the most similar to how I was envisioning my final product

## Relevant Literature

Build a **ten** item literature review for work related to your questions. 

As you consider which 10 to include, try to satisfy these criteria:

- 1 - 2 written by someone on the inside or system impacted
- 3ish non-academic sources
- at least 5 academic sources
- no more than 2 items that we've discussed in class / from the syllabus

No need to include a full citation.  Instead, list them:

**[Mapping Prison Proliferation: Region, rurality, race and disadvantage in prison placement](https://static1.squarespace.com/static/631b1bc54d4b3d277179851d/t/646cf9674e16115e6ddef152/1684863335171/Eason_Mapping+prison+proliferation.pdf):** This article discusses the theory that prisons are built in poor white towns in order to exploit the labor of Black and Brown prisoners. I want to research the demographics of the towns and what factors go into the building of prisons, both of which are examined in this article.


**[“Not in my backyard”: The issues and complexities surrounding prison siting](https://www.tandfonline.com/doi/pdf/10.1080/1478601X.1999.9959532):** This article focuses on the different approaches behind choosing the site of a prison, and also gives some attention to the residents’ opinion. Exploring the reasoning behind building a prison is one of my research questions.  


**[Mass Incarceration and the Paradox of Prison Conditions Litigation Schoenfeld The Paradox of Prison Conditions Litigation](https://research.ebsco.com/plink/ee4f8c73-4d7a-31cb-b6e3-6f93cf872311):** The author examines how building into prisons/increasing incarceration can come from rulings that had the opposite intention. This relates to my question of the causes of prison siting.


**[Are Prisons Obsolete?](https://research.ebsco.com/c/4e4lys/search/details/u57umayqib?request-context=plink&db=nlebk&db=nlabk):** She discusses prison distribution in California, and the prison industrial complex chapter has discussion of why prisons are built and by who. I appreciate having a source that discusses prison distribution outside of a data set. This is also one of the few sources I found that discusses why prisons are built


**[Punishment is Purple: The Political Economy of Prison Building](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4473836):** Given that mass incarceration is a result of the prison boom, this article disproves the notion that republican legislators are the ones responsible for that boom, and it actually is the result of bipartisan voting. This offers a new reasoning behind the decision to build prisons.


**[Prisons as Panacea or Pariah? The Countervailing Consequences of the Prison Boom on the Political Economy of Rural Towns](https://www.mdpi.com/2076-0760/6/1/7):** The paper shows how economic decline slowed after prisons were built. This reveals possible motivation for building prisons, and supports my initial hypothesis about motivations.


**[Debunking Four Myths about the Prison Building Boom Supporting Mass Incarceration](https://www.urban.org/urban-wire/debunking-four-myths-about-prison-building-boom-supporting-mass-incarceration):** Like the title says, this article talks about four myths about the purpose of prisons: prison towns are tiny, white towns; prison building has been led by republicans; prisons don’t benefit the towns they are built in; and mass incarceration is an urban problem. This article also links other scholarly sources that I could use.


**[New York state seeking proposals to build new prison](https://spectrumlocalnews.com/nys/central-ny/news/2026/09/11/new-york-state-seeking-proposals-to-build-a-new-prison):** This is the statement put out by legislators to build a new prison. A statement from the perspective of the people in power is only one side of the story, but useful for comparing to other motivations

**[Site of former Stateville Correctional Facility to house new prisons, officials say](https://www.nbcchicago.com/news/local/crest-hill-will-soon-be-home-to-new-prisons-illinois-officials-say/3945627/):** Same as above, but in Chicago. It has the same benefits, featuring a main reasoning of new jobs.

**[Prison Town, USA](https://www.pbs.org/pov/films/prisontown/?):** A documentary that takes a look at people that live in Susanville, CA (small, rural town in the northeastern part of CA that tries to resuscitate its economy by accepting the construction of a state prison). It follows a mill worker who becomes a correctional officer, a local business owner, and the family of an incarcerated person
